### ISSUE TITLE
Algolia skips pre-rendering the indexable documents on Netlify

### ISSUE THREAD

**Issue by richardgazdik** [algolia/jekyll-algolia#124]
I have a strange issue with Netlify. When I push the changes to my remote git branch and Netlify starts to deploy then it seems that it completely skips the  pre-rendering process of the indexable documents.

### What is the current behavior?
Everything works normally in my local branch and correctly get the following log with `--verbose`:
```
Rendering: _pages/support/troubleshooting/2017-01-01-import-psd-ai.md
Pre-Render Hooks: _pages/support/troubleshooting/2017-01-01-import-psd-ai.md
Rendering Markup: _pages/support/troubleshooting/2017-01-01-import-psd-ai.md
Rendering Layout: _pages/support/troubleshooting/2017-01-01-import-psd-ai.md
```

but these lines are completely missing from the Netlify log.
Which means that all the markdown and liquid syntaxes remain unchanged during the update and Algolia can’t detect any `<p>` tags in the content. It can't split the indexable content into smaller chunks which is resulting a large record size and the deploy runs into an error.

### What is your expected behavior?
I'd like to upload the same records on Netlify and in my local environment.

### Ruby version used:
2.6.0

### Jekyll version used:
jekyll 3.8.5, jekyll-algolia (1.4.11)

```
algolia:
  application_id: '****'
  index_name: 'knowledge_base_staging'
  max_record_size: 10000
  nodes_to_index: 'h1,h2,h3,h4,h5,p,ol,ul'
  # files_to_exclude are now defined via a Jekyll plugin. See _plugins/algolia-include-filter.rb
  settings:
    highlightPreTag: '<span class="algolia__result-highlight">'
    highlightPostTag: '</span>'
    searchableAttributes:
      - title
      - description
      - keywords
      - headings
      - content
      - tags
      - categories
    customRanking:
      - asc(faq-order)
    typoTolerance: strict
    ignorePlurals: true
    removeStopWords: true
    synonyms:
      - ['account', 'license', 'serial', 'key']
      - ['app store', 'appstore', 'mas']
      - ['inspector', 'properties', 'right panel']
      - ['seat', 'machine', 'user', 'device', 'computer']
      - ['requirements', 'specifications', 'spec']
      - ['menu', 'pane', 'panel']
      - ['preferences', 'settings']
      - ['layer list', 'left panel', 'layers list']
      - ['bitmap images', 'jpeg images', 'png images']
      - ['washed out', 'faded']
```
