### ISSUE TITLE
Content w/in tables not indexed

### ISSUE THREAD

**Issue by clairealyssa** [algolia/jekyll-algolia#128]
### What is the current behavior?
Jekyll-algolia does not seem to be including content within tables in the index.
(I apologize if this is better suited to the forum, but it feels like a bug _and_ I am getting a 403 error when I try to submit there.) It looks like this impacts both markdown and html tables.

For example, I have a table of fields and descriptions. One such field is "Mandatory", the table is pretty much like the one below, just with several more rows.

|Field|Description|
|--- |--- |
|Mandatory|Description of the mandatory field|

When I search for mandatory in my search, I get no results found (this is the only instance of the term mandatory in my content).

### What is your expected behavior?
I would expect table content to be included in the index (within "content").

### Git repository to reproduce the issue:
I can't provide access to the repository. However, here is my config:
```
algolia:
  application_id: //
  index_name: //
  search_only_api_key: //
  files_to_exclude:
   - search.html
   - index.html
   - 404.html
  settings:
    searchableAttributes:
      - title
      - headings
      - content
      - roles
      - application
    attributesForFaceting:
      - application
      - roles
    attributesToHighlight:
      - title
      - headings
      - content
    attributesToSnippet:
      - content:20
      - excerpt_text:10
    customRanking:
      - asc(application)
      - asc(title)
      - desc(custom_ranking.position)
```
### Ruby version used:
ruby 2.4.4p296

### Jekyll version used:
jekyll 3.8.5
