### ISSUE TITLE
Question: Is it possible to index items nested in a sub-folder in a site data file?

### ISSUE THREAD

**Issue by gitjul** [algolia/jekyll-algolia#144]
## How can I index items in a data file subfolder?

For example, using an example from the Jekyll docs, how would I index members specified in `_data/orgs/jekyll.yml` like below?

```
username: jekyll
name: Jekyll
members:
  - name: Tom Preston-Werner
    github: mojombo

  - name: Parker Moore
    github: parkr
```

I can't remove the nesting.

### Ruby version used:
2.6.3p62

### Jekyll version used:
4.0.0
