### ISSUE TITLE
Provide more hooks parameters

### ISSUE THREAD

**Issue by nfrankel** [algolia/jekyll-algolia#46]
_I want to suggest a feature:_

The issue I'm currently facing is that I want to index multi-dimensionnal author data along with the content instead of a simple string. The data is available in one of the `_data` file.

Here's a snippet of the data file I want to use:

```
main:
    firstName: John
    lastName: Doe
    job: Developer
    company: Geek
    url: me
    image: assets/resources/me/me.jpg
```

I'd suggest a change in the `before_indexing_each(record, node)` method to also add the `site` parameter (which would also let access the configuration, etc.).
