### ISSUE TITLE
Attributes to snippet setting not correctly pushed

### ISSUE THREAD

**Issue by pixelastic** [algolia/jekyll-algolia#49]
### What is the current behavior?

Every time I push to algolia, it just duplicates all the records.
Also, not all the settings are copied , or updated to the index
For example:
```yaml
algolia:
  settings:
    attributesToSnippet: ['content:10']
```
rendered:
![image](https://user-images.githubusercontent.com/283419/36784123-939e891a-1c7e-11e8-90c1-1695e872134c.png)

---
Originally posted here https://github.com/algolia/jekyll-algolia/issues/39
